mysql:
  image: tuxpiper/ushahidi-platform-mysql:latest
api:
  image: tuxpiper/ushahidi-platform:latest
  links:
    - mysql:mysql
  volumes:
    - /var/run/php-fpm.sock
client:
  build: tuxpiper/ushahidi-platform-client:latest
nginx:
  image: tuxpiper/ushahidi-platform-nginx:latest
  links:
    - client:client
    - api:api
